version: "3.9"

services:
  bot2-program:
    build: ./bot2
    container_name: bot2-program
    image: inventory-finder_bot2-program:latest
    volumes:
      - ./files:/app/data
    networks:
      - app-network
    env_file:
      - .env    
  # bot-program:
  #   build: ./bot
  #   container_name: bot-program
  #   image: inventory-finder_bot-program:latest
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #   networks:
  #     - app-network   
  # products-server:
  #   build: ./products
  #   container_name: product-service
  #   image: inventory-finder_products-server:latest
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./products:/app
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=5000
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  # users-server:
  #   build: ./users
  #   container_name: user-service
  #   image: inventory-finder_users-server:latest
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - ./users:/app
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=5001
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-data:/data
  #   networks:
  #     - app-network
networks:
  app-network: 
    driver: bridge
# volumes:
#   redis-data:
    