version: "3.9"

services:
  bot2-program:
    build: ./bot2
    container_name: bot2-program
    image: inventory-finder_bot2-program:latest
    volumes:
      - ./files:/app/data
    networks:
      - app-network
    env_file:
      - .env 
  # bot-program:
  #   build: ./bot
  #   container_name: bot-program
  #   image: inventory-finder_bot-program
  #   volumes:
  #     - ./bot:/app
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network   
  # products-server:
  #   build: 
  #     context: ./products
  #     dockerfile: Dockerfile.dev
  #   container_name: product-service
  #   image: inventory-finder_products-server
  #   volumes:
  #     - ./products:/app
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=5000
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  # reports-server:
  #   build: 
  #     context: ./reports
  #     dockerfile: Dockerfile.dev
  #   container_name: report-service
  #   image: inventory-finder_reports-server
  #   volumes:
  #     - ./reports:/app
  #     - ./files:/app/files      
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=5002
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network      
  # users-server:
  #   build: 
  #     context: ./users
  #     dockerfile: Dockerfile.dev
  #   container_name: user-service
  #   image: inventory-finder_users-server
  #   volumes:
  #     - ./users:/app
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=5001
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network
  # proxy-server:
  #   build: 
  #     context: ./proxy
  #     dockerfile: Dockerfile.dev
  #   container_name: proxy-service
  #   image: inventory-finder_proxy-server
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./proxy:/app
  #   depends_on:
  #     # - products-server
  #     - users-server
  #   environment:
  #     - PORT=4000
  #     - PRODUCTS_SERVICE_URL=http://products-server:5000
  #     - USERS_SERVICE_URL=http://users-server:5001
  #     - REPORTS_SERVICE_URL=http://reports-server:5002
  #   env_file:
  #     - .env
  #   networks:
  #     - app-network    
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   volumes:
  #     - ./redis-data:/data
  #   networks:
  #     - app-network
networks:
  app-network: 
    driver: bridge
# volumes:
#   redis-data:
    